services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: mysql8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "Zhy26825.+8"
      MYSQL_ROOT_HOST: "localhost"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql
      - ./mysql/mysql-conf:/etc/mysql/conf.d
    command:
      [
        "--default-authentication-plugin=caching_sha2_password",
        "--bind-address=0.0.0.0",
      ]
    networks:
      - app-network

  # Redis 缓存
  redis:
    image: redis:7.0
    container_name: redis7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis-data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - app-network

  # RabbitMQ 消息队列
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq3
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=hutongsk
      - RABBITMQ_DEFAULT_PASS=hutongsk123
    volumes:
      - ./rabbit-compose/rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  # Nacos 注册中心
  nacos:
    image: nacos/nacos-server:v3.0.3
    container_name: nacos3
    restart: always
    environment:
      - MODE=standalone
      - SPRING_DATASOURCE_URL=jdbc:mysql://43.226.46.171:33066/sknacos?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=43.226.46.171
      - MYSQL_SERVICE_PORT=33066
      - MYSQL_SERVICE_DB_NAME=sknacos
      - MYSQL_SERVICE_USER=OnePiece
      - MYSQL_SERVICE_PASSWORD=Zhy26825.+8
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_TOKEN=Ui0YwTlSg4dAE96B8lI1BVDs/0mOuFxPPITFHx+vdIQ=
      - NACOS_AUTH_IDENTITY_KEY=nacos_identity_key
      - NACOS_AUTH_IDENTITY_VALUE=nacos_identity_value
    volumes:
      - ./nacos/logs:/home/nacos/logs
    ports:
      - "8848:8848"
      - "8080:8080"
      - "9848:9848"
      - "9849:9849"
    depends_on:
      - mysql
    networks:
      - app-network

  # Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/logs:/var/log/nginx
    environment:
      - TZ=Asia/Shanghai
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
