services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq3
    restart: always
    ports:
      - "5672:5672"   # AMQP 协议端口（客户端连接）
      - "15672:15672" # Web 管理界面
    environment:
      - RABBITMQ_DEFAULT_USER=hutongsk # 请务必修改为强用户名
      - RABBITMQ_DEFAULT_PASS=hutongsk123 # 请务必修改为强密码
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq   # 持久化数据（包括消息、配置、插件）
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
